version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: voting_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: vote_app
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/app

volumes:
  mysql_data:
